name: Java CI with JUnit

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java files (excluding Randoop-generated tests)
        run: |
          echo "Compiling Java files..."
          mkdir -p bin
          find . -name "*.java" \
            -not -name "*Regression*.java" \
            -not -name "*ErrorTest*.java" \
            -not -name "*Randoop*.java" > sources.txt
          javac -d bin -cp "lib/*" @sources.txt

      - name: Run JUnit tests
        run: |
          echo "Running JUnit tests..."
          LIB_CP=$(find lib -name "*.jar" | tr '\n' ':')
          java -jar lib/junit-platform-console-standalone-1.12.0.jar \
            --class-path "bin:$LIB_CP" \
            --scan-class-path \
            --include-classname=".*(Test|JUnit)"
